apiVersion: v1
kind: Service
metadata:
  name: kanban-app-svc
spec:
  type: NodePort
  ports:
    - name: appport
      port: 8080
      targetPort: 8080
  selector: 
      role: kanbanapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app-deploy
  labels:     
    role: kanbanapp
spec:
  selector:
    matchLabels:
      role: kanbanapp
  template:
    metadata:
      labels:
        role: kanbanapp
    spec:        
      containers:
       - name: kanban-app
         image: ./kanban-app
         env:
           - name: DB_SERVER
             value: kanban-db-svc      
         ports:
           - name: http
             containerPort: 8080
