apiVersion: v1
kind: Service
metadata:
  name: kanban-db-svc
spec:
  type: NodePort
  ports:
    - name: dbport
      port: 5432
      targetPort: 5432
  selector: 
      role: kanbandb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanban-data-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kanban-db-deploy
    labels:   
      role: kanbandb
spec:
  replicas: 4
  selector:
    matchLabels:
      role: kanbandb
  template:
    metadata:
      labels:
        role: kanbandb
    spec:
      containers:
          - name: kanban-postgres
            image: postgres:9.6-alpine
            env:
              - name: POSTGRES_DB
                value: kanban
              - name: POSTGRES_USER
                value: kanban
              - name: POSTGRES_PASSWORD
                value: kanban
              - name: PGDATA
                value: /var/lib/postgresql/data/pgdata
            ports:
                - name: db
                  containerPort: 5432
            volumeMounts:
              - name: kanban-data
                mountPath: /var/lib/postgresql/data        
      volumes:
           - name: kanban-data
             persistentVolumeClaim:
               claimName: kanban-data-pvc    
      nodeSelector:
        argocd: "true"
