---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    volume: pv0001
  name: pv0001
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data
    type: ""
